"""
Ant Colony Optimization for Continuous Domains (ACOR)
======================================================
Implements the ACOR variant (Socha & Dorigo, 2008) adapted for the
[0,1]^9 encoded hyperparameter space.

Algorithm:
  1. Maintain a solution archive of K=10 best solutions found so far.
  2. Each iteration, n_ants=5 new solutions are generated by sampling
     Gaussian kernels centred on archive solutions (weighted by rank).
  3. Archive is updated by keeping the K best across old archive + new ants.
  4. Pheromone evaporation is controlled by xi=0.85 (archive weight spread).

Isaac Gym compatibility:
  No changes needed — fitness_fn is called via BaseOptimizer._evaluate().
"""

import numpy as np
from src.optimizers.base_optimizer import BaseOptimizer


class ACOOptimizer(BaseOptimizer):
    """
    Ant Colony Optimizer (continuous ACOR) for hyperparameter search.

    Args:
        fitness_fn : Callable hp_dict -> float.
        hp_space   : hp_space module (unused directly).
        n_evals    : Total evaluation budget (default 50).
        seed       : Random seed (default 42).
        archive_k  : Archive size (default 10).
        n_ants     : Ants per iteration (default 5).
        xi         : Pheromone evaporation / weight spread (default 0.85).
    """

    def __init__(
        self,
        fitness_fn,
        hp_space=None,
        n_evals: int = 50,
        seed: int = 42,
        archive_k: int = 10,
        n_ants: int = 5,
        xi: float = 0.85,
    ):
        super().__init__(
            fitness_fn=fitness_fn,
            hp_space=hp_space,
            n_evals=n_evals,
            seed=seed,
            optimizer_name="ACO",
        )
        self.archive_k = archive_k
        self.n_ants    = n_ants
        self.xi        = xi

    def _gaussian_weights(self, archive_size: int) -> np.ndarray:
        """
        Compute selection probabilities for archive solutions using
        rank-based Gaussian weights (ACOR formula).

        w_l = 1/(xi * K * sqrt(2pi)) * exp(-((l-1)^2)/(2*xi^2*K^2))

        Returns normalised probabilities of shape (archive_size,).
        """
        l   = np.arange(1, archive_size + 1, dtype=float)
        K   = float(archive_size)
        w   = np.exp(-((l - 1.0) ** 2) / (2.0 * self.xi ** 2 * K ** 2))
        return w / w.sum()

    def _sample_from_archive(self, archive: np.ndarray,
                             archive_fits: np.ndarray) -> np.ndarray:
        """
        Generate a new solution by sampling a Gaussian kernel centred on a
        selected archive solution.

        Standard deviation for each dimension is the mean pairwise distance
        of all archive solutions in that dimension (ACOR sigma formula).
        """
        # Sort archive by fitness (descending) — best first
        order        = np.argsort(archive_fits)[::-1]
        sorted_arch  = archive[order]

        probs        = self._gaussian_weights(len(archive))
        chosen_idx   = self.rng.choice(len(archive), p=probs)
        centre       = sorted_arch[chosen_idx]

        # Sigma: mean distance from chosen centre to all archive points
        sigma = np.mean(np.abs(sorted_arch - centre), axis=0) + 1e-8

        # Sample new solution
        new_sol = centre + self.rng.normal(0.0, 1.0, size=self._dim) * sigma
        return np.clip(new_sol, 0.0, 1.0)

    def _run(self) -> None:
        """Execute ACOR optimization loop."""
        # Seed archive with random solutions
        init_size = min(self.archive_k, self._budget_remaining())
        archive      = np.zeros((init_size, self._dim))
        archive_fits = np.full(init_size, -np.inf)

        print(f"\n[ACO] Starting | K={self.archive_k} | ants/iter={self.n_ants} "
              f"| xi={self.xi} | budget={self.n_evals}")

        for i in range(init_size):
            if self._budget_remaining() <= 0:
                break
            vec           = self._random_vector()
            archive[i]    = vec
            archive_fits[i] = self._evaluate(vec)

        iteration = 0
        while self._budget_remaining() > 0:
            iteration += 1
            new_sols  = []
            new_fits  = []

            for _ in range(self.n_ants):
                if self._budget_remaining() <= 0:
                    break
                new_sol = self._sample_from_archive(archive, archive_fits)
                f       = self._evaluate(new_sol)
                new_sols.append(new_sol)
                new_fits.append(f)

            # Merge archive + new ants, keep top-K
            all_sols  = np.vstack([archive, np.array(new_sols)])
            all_fits  = np.concatenate([archive_fits, np.array(new_fits)])
            top_idx   = np.argsort(all_fits)[-self.archive_k:]
            archive       = all_sols[top_idx]
            archive_fits  = all_fits[top_idx]

            print(f"  Iter {iteration:3d} | archive_best={archive_fits.max():.4f} | "
                  f"evals={self._eval_count}/{self.n_evals}")

        print(f"[ACO] Done | best_fitness={self._best_fitness:.4f} "
              f"| evals={self._eval_count}")
